---
- name: lb and web orchestration
  hosts: web
  serial: 2
  tasks:
   - name: disable node
     debug:
       msg: disable {{ inventory_hostname }}
     delegate_to: "{{ groups['lb'][0] }}"
   - name: upgrade app
     debug:
       msg: upgrade software
   - name: enable node
     debug:
       msg: enable {{ inventory_hostname }}
     delegate_to: "{{ groups['lb'][0] }}"